<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ProblemReportNotificationService"
		targetNamespace="http://www.kapsch.hr/cadb/schemas/ProblemReportNotificationService"
		xmlns="http://schemas.xmlsoap.org/wsdl/"
		xmlns:tns="http://www.kapsch.hr/cadb/schemas/ProblemReportNotificationService"
		xmlns:fault="http://www.kapsch.hr/cadb/schemas/fault" 
		xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<types>
		<xsd:schema targetNamespace="http://www.kapsch.hr/cadb/schemas/ProblemReportNotificationService">
			<xsd:include schemaLocation="../xsd/problemNotification.xsd"/>
		</xsd:schema>
		<xsd:schema targetNamespace="http://www.kapsch.hr/cadb/schemas/fault">
			<xsd:include schemaLocation="../xsd/fault.xsd"/>
		</xsd:schema>
	</types>

	<message name="NotifyProblemReportedRequestMessage">
		<part name="body" element="tns:notifyProblemReportedRequest"/>
	</message>

	<message name="NotifyProblemReportedResponseMessage">
		<part name="body" element="tns:notifyProblemReportedResponse"/>
	</message>

	<message name="LdbAdministrationServiceFaultMessage">
		<part name="body" element="fault:ldbAdministrationServiceFault"/>
	</message>

	<portType name="ProblemReportNotificationServicePortType">
		<operation name="notifyProblemReported">
			<input message="tns:NotifyProblemReportedRequestMessage"/>
			<output message="tns:NotifyProblemReportedResponseMessage"/>
			<fault name="ldbAdministrationServiceFault" message="tns:LdbAdministrationServiceFaultMessage"/>
		</operation>
	</portType>

	<binding name="ProblemReportNotificationServiceBinding" type="tns:ProblemReportNotificationServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<operation name="notifyProblemReported">
			<soap:operation soapAction="notifyProblemReported"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ldbAdministrationServiceFault">
				<soap:fault name="ldbAdministrationServiceFault" use="literal"/>
			</fault>
		</operation>
	</binding>

	<service name="ProblemReportNotificationService">
		<port name="ProblemReportNotificationServicePort" binding="tns:ProblemReportNotificationServiceBinding">
			<soap:address location="http://172.21.75.34/SGP/cadb/ProblemReportNotificationService"/>
		</port>
	</service>

</definitions>
