<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class config_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get config by key
     */
    function get_config($key)
    {
        $response = $this->db->get_where('config',array('key'=>$key))->row_array();

        if($response){
            return $response['value'];
        }else{
            return null;
        }
    }

    /*
     * Get all config
     */
    function get_all_config()
    {
        return $this->db->get('config')->result_array();
    }
    
    /*
     * function to add new config
     */
    function add_config($params)
    {
        $this->db->insert('config',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update config
     */
    function update_error($key,$params)
    {
        $this->db->where('key',$key);
        $response = $this->db->update('config',$params);
        if($response)
        {
            return "config updated successfully";
        }
        else
        {
            return "config occurring while updating error";
        }
    }

}
