<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get log by logId
     */
    function get_log($logId)
    {
        return $this->db->get_where('log',array('logId'=>$logId))->row_array();
    }
    
    /*
     * Get all log
     */
    function get_all_log()
    {
        return $this->db->get('log')->result_array();
    }
    
    /*
     * function to add new log
     */
    function add_log($params)
    {
        $params = $this->reformatDates($params);
        $this->db->insert('log',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update log
     */
    function update_log($logId,$params)
    {
        $params = $this->reformatDates($params);
        $this->db->where('logId',$logId);
        $response = $this->db->update('log',$params);
        if($response)
        {
            return "log updated successfully";
        }
        else
        {
            return "Error occuring while updating log";
        }
    }
    
    /*
     * function to delete log
     */
    function delete_log($logId)
    {
        $response = $this->db->delete('log',array('logId'=>$logId));
        if($response)
        {
            return "log deleted successfully";
        }
        else
        {
            return "Error occuring while deleting log";
        }
    }

    private function reformatDates($params){

        // Log
        if(isset($params['actionDateTime'])){
            $params['actionDateTime'] = date('Y-m-d\TH:i:s', strtotime($params['actionDateTime']));
        }

        return $params;

    }

}
