<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Numberreturnsubmission_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get numberreturnsubmission by numberReturnSubmissionId
     */
    function get_numberreturnsubmission($numberReturnSubmissionId)
    {
        return $this->db->get_where('NumberReturnSubmission',array('numberReturnSubmissionId'=>$numberReturnSubmissionId))->row_array();
    }

    /*
     * Get numberreturnsubmission by state
     */
    function get_submissionByState($submissionState)
    {
        return $this->db->get_where('NumberReturnSubmission',array('submissionState'=>$submissionState))->result_array();
    }
    
    /*
     * Get all numberreturnsubmission
     */
    function get_all_numberreturnsubmission()
    {
        return $this->db->get('NumberReturnSubmission')->result_array();
    }
    
    /*
     * function to add new numberreturnsubmission
     */
    function add_numberreturnsubmission($params)
    {
        $this->db->insert('NumberReturnSubmission',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update numberreturnsubmission
     */
    function update_numberreturnsubmission($numberReturnSubmissionId,$params)
    {
        $this->db->where('numberReturnSubmissionId',$numberReturnSubmissionId);
        $response = $this->db->update('NumberReturnSubmission',$params);
        if($response)
        {
            return "numberreturnsubmission updated successfully";
        }
        else
        {
            return "Error occuring while updating numberreturnsubmission";
        }
    }
    
    /*
     * function to delete numberreturnsubmission
     */
    function delete_numberreturnsubmission($numberReturnSubmissionId)
    {
        $response = $this->db->delete('NumberReturnSubmission',array('numberReturnSubmissionId'=>$numberReturnSubmissionId));
        if($response)
        {
            return "numberreturnsubmission deleted successfully";
        }
        else
        {
            return "Error occuring while deleting numberreturnsubmission";
        }
    }
}
