<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Portingsmsnotification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get portingsmsnotification by portingSmsNotificationId
     */
    function get_portingsmsnotification($portingSmsNotificationId)
    {
        return $this->db->get_where('portingsmsnotification',array('portingSmsNotificationId'=>$portingSmsNotificationId))->row_array();
    }

    /*
     * Get portingsmsnotification by status
     */
    function get_portingsmsnotificationByStatus($status)
    {
        return $this->db->get_where('portingsmsnotification',array('status'=>$status))->result_array();
    }


    /*
     * Get all portingsmsnotification
     */
    function get_all_portingsmsnotification()
    {
        return $this->db->get('portingsmsnotification')->result_array();
    }
    
    /*
     * function to add new portingsmsnotification
     */
    function add_portingsmsnotification($params)
    {
        $params = $this->reformatDates($params);
        $this->db->insert('portingsmsnotification',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update portingsmsnotification
     */
    function update_portingsmsnotification($portingSmsNotificationId,$params)
    {
        $params = $this->reformatDates($params);
        $this->db->where('portingSmsNotificationId',$portingSmsNotificationId);
        $response = $this->db->update('portingsmsnotification',$params);
        if($response)
        {
            return "portingsmsnotification updated successfully";
        }
        else
        {
            return "Error occuring while updating portingsmsnotification";
        }
    }
    
    /*
     * function to delete portingsmsnotification
     */
    function delete_portingsmsnotification($portingSmsNotificationId)
    {
        $response = $this->db->delete('portingsmsnotification',array('portingSmsNotificationId'=>$portingSmsNotificationId));
        if($response)
        {
            return "portingsmsnotification deleted successfully";
        }
        else
        {
            return "Error occuring while deleting portingsmsnotification";
        }
    }

    private function reformatDates($params){

        // Porting SMS Notification
        if(isset($params['creationDateTime'])){
            $params['creationDateTime'] = date('Y-m-d\TH:i:s', strtotime($params['creationDateTime']));
        }
        if(isset($params['sendDateTime'])){
            $params['sendDateTime'] = date('Y-m-d\TH:i:s', strtotime($params['sendDateTime']));
        }

        return $params;

    }

}
