<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Portingsubmission_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get portingsubmission by portingSubmissionId
     */
    function get_portingsubmission($portingSubmissionId)
    {
        return $this->db->get_where('PortingSubmission',array('portingSubmissionId'=>$portingSubmissionId))->row_array();
    }

    /*
     * Get portingsubmission by portingId
     */
    function get_submissionByPortingId($portingId)
    {
        $query = "SELECT p1.`contractId`, p1.`temporalMSISDN` FROM porting p INNER JOIN portingsubmission p1 ON 
                  ( p.`portingSubmissionId` = p1.`portingSubmissionId`) WHERE p.portingId = '" . $portingId . "'";

        $response = $this->db->query($query)->row_array();

        return $response;
    }

    /*
     * Get portingsubmission by state
     */
    function get_submissionByState($submissionState)
    {
        return $this->db->get_where('PortingSubmission',array('submissionState'=>$submissionState))->result_array();
    }
    
    /*
     * Get all portingsubmission
     */
    function get_all_portingsubmission()
    {
        return $this->db->get('PortingSubmission')->result_array();
    }
    
    /*
     * function to add new portingsubmission
     */
    function add_portingsubmission($params)
    {
        $this->db->insert('PortingSubmission',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update portingsubmission
     */
    function update_portingsubmission($portingSubmissionId,$params)
    {
        $this->db->where('portingSubmissionId',$portingSubmissionId);
        $response = $this->db->update('PortingSubmission',$params);
        if($response)
        {
            return "portingsubmission updated successfully";
        }
        else
        {
            return "Error occuring while updating portingsubmission";
        }
    }
    
    /*
     * function to delete portingsubmission
     */
    function delete_portingsubmission($portingSubmissionId)
    {
        $response = $this->db->delete('PortingSubmission',array('portingSubmissionId'=>$portingSubmissionId));
        if($response)
        {
            return "portingsubmission deleted successfully";
        }
        else
        {
            return "Error occuring while deleting portingsubmission";
        }
    }
}
