<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Portingdenyrejectionabandon_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get portingdenyrejectionabandon by portingDenyRejectionAbandonedId
     */
    function get_portingdenyrejectionabandon($portingDenyRejectionAbandonedId)
    {
        return $this->db->get_where('PortingDenyRejectionAbandon',array('portingDenyRejectionAbandonedId'=>$portingDenyRejectionAbandonedId))->row_array();
    }
    
    /*
     * Get all portingdenyrejectionabandon
     */
    function get_all_portingdenyrejectionabandon()
    {
        return $this->db->get('PortingDenyRejectionAbandon')->result_array();
    }
    
    /*
     * function to add new portingdenyrejectionabandon
     */
    function add_portingdenyrejectionabandon($params)
    {
        $this->db->insert('PortingDenyRejectionAbandon',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update portingdenyrejectionabandon
     */
    function update_portingdenyrejectionabandon($portingDenyRejectionAbandonedId,$params)
    {
        $this->db->where('portingDenyRejectionAbandonedId',$portingDenyRejectionAbandonedId);
        $response = $this->db->update('PortingDenyRejectionAbandon',$params);
        if($response)
        {
            return "portingdenyrejectionabandon updated successfully";
        }
        else
        {
            return "Error occuring while updating portingdenyrejectionabandon";
        }
    }
    
    /*
     * function to delete portingdenyrejectionabandon
     */
    function delete_portingdenyrejectionabandon($portingDenyRejectionAbandonedId)
    {
        $response = $this->db->delete('PortingDenyRejectionAbandon',array('portingDenyRejectionAbandonedId'=>$portingDenyRejectionAbandonedId));
        if($response)
        {
            return "portingdenyrejectionabandon deleted successfully";
        }
        else
        {
            return "Error occuring while deleting portingdenyrejectionabandon";
        }
    }
}
