<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Returnrejection_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get returnrejection by returnRejectionId
     */
    function get_returnrejection($returnRejectionId)
    {
        return $this->db->get_where('ReturnRejection',array('returnRejectionId'=>$returnRejectionId))->row_array();
    }
    
    /*
     * Get all returnrejection
     */
    function get_all_returnrejection()
    {
        return $this->db->get('ReturnRejection')->result_array();
    }
    
    /*
     * function to add new returnrejection
     */
    function add_returnrejection($params)
    {
        $this->db->insert('ReturnRejection',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update returnrejection
     */
    function update_returnrejection($returnRejectionId,$params)
    {
        $this->db->where('returnRejectionId',$returnRejectionId);
        $response = $this->db->update('ReturnRejection',$params);
        if($response)
        {
            return "returnrejection updated successfully";
        }
        else
        {
            return "Error occuring while updating returnrejection";
        }
    }
    
    /*
     * function to delete returnrejection
     */
    function delete_returnrejection($returnRejectionId)
    {
        $response = $this->db->delete('ReturnRejection',array('returnRejectionId'=>$returnRejectionId));
        if($response)
        {
            return "returnrejection deleted successfully";
        }
        else
        {
            return "Error occuring while deleting returnrejection";
        }
    }
}
