<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Returnsmsnotification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get returnsmsnotification by returnSmsNotificationId
     */
    function get_returnsmsnotification($returnSmsNotificationId)
    {
        return $this->db->get_where('returnsmsnotification',array('returnSmsNotificationId'=>$returnSmsNotificationId))->row_array();
    }
    
    /*
     * Get all returnsmsnotification
     */
    function get_all_returnsmsnotification()
    {
        return $this->db->get('returnsmsnotification')->result_array();
    }
    
    /*
     * function to add new returnsmsnotification
     */
    function add_returnsmsnotification($params)
    {
        $this->db->insert('returnsmsnotification',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update returnsmsnotification
     */
    function update_returnsmsnotification($returnSmsNotificationId,$params)
    {
        $this->db->where('returnSmsNotificationId',$returnSmsNotificationId);
        $response = $this->db->update('returnsmsnotification',$params);
        if($response)
        {
            return "returnsmsnotification updated successfully";
        }
        else
        {
            return "Error occuring while updating returnsmsnotification";
        }
    }
    
    /*
     * function to delete returnsmsnotification
     */
    function delete_returnsmsnotification($returnSmsNotificationId)
    {
        $response = $this->db->delete('returnsmsnotification',array('returnSmsNotificationId'=>$returnSmsNotificationId));
        if($response)
        {
            return "returnsmsnotification deleted successfully";
        }
        else
        {
            return "Error occuring while deleting returnsmsnotification";
        }
    }
}
