<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Rollbacksubmission_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rollbacksubmission by rollbackSubmissionId
     */
    function get_rollbacksubmission($rollbackSubmissionId)
    {
        return $this->db->get_where('rollbacksubmission',array('rollbackSubmissionId'=>$rollbackSubmissionId))->row_array();
    }

    /*
     * Get rollback submission by state
     */
    function get_submissionByState($submissionState)
    {
        return $this->db->get_where('rollbacksubmission',array('submissionState'=>$submissionState))->result_array();
    }

    /*
     * Get rollbacksubmission by rollbackId
     */
    function get_submissionByRollbackId($rollbackId)
    {
        $query = "SELECT p1.`contractId`, p1.`temporalMSISDN` FROM rollback p INNER JOIN rollbacksubmission p1 ON 
                  ( p.`rollbackSubmissionId` = p1.`rollbackSubmissionId`) WHERE p.rollbackId = '" . $rollbackId . "'";

        $response = $this->db->query($query)->row_array();

        return $response;
    }


    /*
     * Get all rollbacksubmission
     */
    function get_all_rollbacksubmission()
    {
        return $this->db->get('rollbacksubmission')->result_array();
    }
    
    /*
     * function to add new rollbacksubmission
     */
    function add_rollbacksubmission($params)
    {
        $this->db->insert('rollbacksubmission',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rollbacksubmission
     */
    function update_rollbacksubmission($rollbackSubmissionId,$params)
    {
        $this->db->where('rollbackSubmissionId',$rollbackSubmissionId);
        $response = $this->db->update('rollbacksubmission',$params);
        if($response)
        {
            return "rollbacksubmission updated successfully";
        }
        else
        {
            return "Error occuring while updating rollbacksubmission";
        }
    }
    
    /*
     * function to delete rollbacksubmission
     */
    function delete_rollbacksubmission($rollbackSubmissionId)
    {
        $response = $this->db->delete('rollbacksubmission',array('rollbackSubmissionId'=>$rollbackSubmissionId));
        if($response)
        {
            return "rollbacksubmission deleted successfully";
        }
        else
        {
            return "Error occuring while deleting rollbacksubmission";
        }
    }
}
