<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class ussdsmsnotification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ussdsmsnotification by ussdsmsnotificationId
     */
    function get_ussdsmsnotification($ussdsmsnotificationId)
    {
        return $this->db->get_where('USSDSmsNotification',array('ussdsmsnotificationId'=>$ussdsmsnotificationId))->row_array();
    }

    /*
     * Get ussdsmsnotification by status
     */
    function get_ussdsmsnotificationByStatus($status)
    {
        return $this->db->get_where('USSDSmsNotification',array('status'=>$status))->result_array();
    }


    /*
     * Get all ussdsmsnotification
     */
    function get_all_ussdsmsnotification()
    {
        return $this->db->get('USSDSmsNotification')->result_array();
    }
    
    /*
     * function to add new ussdsmsnotification
     */
    function add_ussdsmsnotification($params)
    {

        $this->db->insert('USSDSmsNotification',$params);
        return $this->db->insert_id();

    }
    
    /*
     * function to update ussdsmsnotification
     */
    function update_ussdsmsnotification($ussdsmsnotificationId,$params)
    {
        $this->db->where('ussdsmsnotificationId',$ussdsmsnotificationId);
        $response = $this->db->update('USSDSmsNotification',$params);
        if($response)
        {
            return "ussdsmsnotification updated successfully";
        }
        else
        {
            return "Error occuring while updating ussdsmsnotification";
        }
    }
    
    /*
     * function to delete ussdsmsnotification
     */
    function delete_ussdsmsnotification($ussdsmsnotificationId)
    {
        $response = $this->db->delete('USSDSmsNotification',array('ussdsmsnotificationId'=>$ussdsmsnotificationId));
        if($response)
        {
            return "ussdsmsnotification deleted successfully";
        }
        else
        {
            return "Error occuring while deleting ussdsmsnotification";
        }
    }
}
